apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: openshift-test-app
spec:
  to:
    kind: Service
    name: openshift-test-app
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

    
